<script setup lang="ts">
import { computed, ref } from 'vue'
import { slides } from './deck'
import Icon from './DefenseIcon.vue'
import ProductStage from './ProductStage.vue'
import { parseMoneyToMinor, formatMoney } from '../../utils/money'
const props = defineProps<{ index: number }>()
const emit = defineEmits<{ next: []; jump: [index: number] }>()
const slide = computed(() => slides[props.index]!)
const utterance = ref('午饭 28 元')
const saved = ref(false)
const demoError = ref('')
const parsed = computed(() => {
  const match = utterance.value.match(/(?:^|[^\d.\-])([0-9]+(?:\.[0-9]{1,2})?)(?:\s*元|\s*块|\s*$)/)
  const minor = match ? parseMoneyToMinor(match[1]!) : null
  if (minor === null || minor <= 0 || !Number.isSafeInteger(minor)) return null
  const category = /奶茶|咖啡|午饭|晚饭|早餐/.test(utterance.value) ? '餐饮美食' : /地铁|公交|打车/.test(utterance.value) ? '交通出行' : '其他支出'
  return { minor, category }
})
function record() { if (!parsed.value) { demoError.value = '请输入一笔正数金额，例如“午饭 28 元”。'; return }; saved.value = true; demoError.value = '' }
function sample(text: string) { utterance.value = text; saved.value = false; demoError.value = '' }
</script>
<template>
  <article class="defense-slide" :class="[`slide-${index + 1}`, { 'cover-slide': index === 0 || index === 11 }]" :aria-label="`第 ${index + 1} 页：${slide.title}`">
    <div class="slide-brand"><span><Icon name="book" :size="16" /> RinklNote <i>/</i> 记一笔</span><span>{{ index === 0 ? '项目答辩 · 2026' : slide.section }}</span></div>
    <template v-if="index === 0">
      <div class="cover-layout"><div class="cover-copy"><div class="eyebrow"><span></span> {{ slide.eyebrow }}</div><h1>想记账的人很多，<br>能坚持的人<span class="green-word">很少<svg viewBox="0 0 150 12"><path d="M3 8Q65 0 147 6" /></svg></span>。</h1><p class="cover-subtitle">RinklNote 记一笔</p><p class="cover-description">让年轻人的第一笔账，更容易发生。<br>以 Android 为主入口，用更短路径培养记账习惯。</p><div class="platform-chips"><span><Icon name="phone" :size="14" /> Android 主入口</span><span><Icon name="chat" :size="14" /> QQ Bot 创新</span><span><Icon name="leaf" :size="14" /> 习惯养成</span></div><button class="d-button d-primary start-button" @click="emit('next')">开启项目之旅 <Icon name="arrow" :size="17" /></button><div class="cover-meta"><span>年轻用户 · 低摩擦 · 长期习惯</span><b>12 页 / 约 10 分钟</b></div></div><ProductStage /></div>
    </template>
    <template v-else-if="index === 11">
      <div class="closing"><div class="closing-logo"><Icon name="leaf" :size="38" /></div><div class="eyebrow">{{ slide.eyebrow }}</div><h1>让每一笔，<br>都更有<span class="green-word">意义</span>。</h1><p>{{ slide.description }}</p><div class="closing-actions"><button class="d-button d-primary" @click="emit('jump', 4)">回看 Android 架构 <Icon name="arrow" :size="16" /></button><button class="d-button" @click="emit('jump', 0)">返回封面</button></div><div class="closing-sign">RinklNote 记一笔 <span>记录生活，也读懂生活。</span></div></div>
    </template>
    <template v-else>
      <div class="content-heading"><div class="eyebrow">{{ slide.eyebrow }}</div><h2>{{ slide.heading }}</h2><p>{{ slide.description }}</p></div>
      <div v-if="index === 1" class="pain-grid"><div v-for="(item, i) in [{ icon: 'clock', title: '想记，却总是忘记', text: '下课、下班、聚餐之后，消费发生了，记录的念头却很快消失。', solution: '在想起的瞬间就能记' }, { icon: 'book', title: '想记，却觉得困难', text: '分类、账户、备注和金额同时出现，第一笔就可能让人放弃。', solution: '把复杂选项藏起来' }, { icon: 'chart', title: '记了，却没有动力', text: '只有一串流水，看不到预算变化，也感受不到坚持带来的反馈。', solution: '让每次记录都有回应' }]" :key="item.title" class="pain-card"><span class="card-index">0{{ i + 1 }}</span><Icon :name="item.icon" :size="30" /><h3>{{ item.title }}</h3><p>{{ item.text }}</p><div><Icon name="arrow" :size="16" /> {{ item.solution }}</div></div></div>
      <div v-if="index === 2" class="position-layout"><div class="position-quote"><Icon name="leaf" :size="36" /><blockquote>生活已经很忙，<br>记账可以<span>轻一点。</span></blockquote><p>面向大学生、初入职场的年轻人，<br>从“想记”走向“持续记”。</p></div><div class="position-list"><div v-for="(item, i) in [{ icon: 'phone', title: '想起就能记', text: 'Android 首页保持稳定，打开后直接进入记录。' }, { icon: 'check', title: '记完有反馈', text: '预算、余额和按日账单立即回应这一笔。' }, { icon: 'clock', title: '隔天还想回来', text: '连续记录与温和提醒，帮助习惯慢慢形成。' }]" :key="item.title"><span class="round-icon"><Icon :name="item.icon" /></span><div><h3>{{ item.title }}</h3><p>{{ item.text }}</p></div><b>0{{ i + 1 }}</b></div></div></div>
      <div v-if="index === 3" class="feature-grid"><div v-for="item in [{ icon: 'phone', title: 'Compose UI', text: '声明式页面只关注状态和用户动作，缩短交互反馈链路。', tag: '界面' }, { icon: 'chart', title: 'ViewModel', text: '把输入、加载、成功和错误变成清晰的页面状态。', tag: '状态' }, { icon: 'sync', title: 'StateFlow', text: '账单、余额和预算随着一次记录即时更新。', tag: '反馈' }, { icon: 'shield', title: 'Repository', text: '隔离页面与数据来源，让本地和网络可以平滑切换。', tag: '边界' }, { icon: 'book', title: 'Room v18', text: '本地保存每一笔记录，并通过迁移链保护升级过程。', tag: '持久化' }, { icon: 'arrow', title: '同步 API', text: '网络恢复后增量对齐，异常时保留可重试路径。', tag: '同步' }]" :key="item.title"><span class="round-icon"><Icon :name="item.icon" /></span><small>{{ item.tag }}</small><h3>{{ item.title }}</h3><p>{{ item.text }}</p></div></div>
      <div v-if="index === 4" class="architecture"><div class="architecture-clients"><div><Icon name="phone" /><b>Compose UI</b><small>页面状态 · 交互反馈</small></div><div><Icon name="chart" /><b>ViewModel</b><small>StateFlow · 业务状态</small></div><div><Icon name="book" /><b>Repository + Room</b><small>本地账本 · 迁移链</small></div></div><div class="architecture-connector"><span>用户动作</span><span>状态流</span><span>本地优先</span></div><div class="architecture-server"><span><Icon name="sync" /> 同步边界 · Ktor API</span><div><b>身份鉴权</b><b>增量同步</b><b>冲突保护</b><b>QQ Bot 入账</b></div></div><div class="architecture-storage"><div><Icon name="shield" /><b>记录先落本地</b><span>断网可用 · 可重试</span></div><div><Icon name="chat" /><b>QQ Bot 辅助入口</b><span>同一账本 · 有确认回执</span></div></div></div>
      <div v-if="index === 5" class="android-layout"><div class="android-flow"><div class="flow-tag">习惯回路 · 每一步都给出下一步理由</div><div v-for="(row, i) in [{ title: '想起', detail: '消费发生，或刚好回忆起一笔支出' }, { title: '记录', detail: '金额优先，分类和备注按需补充' }, { title: '确认', detail: '一键确认，看到已加入当天账单' }, { title: '反馈', detail: '预算、余额和连续记录立即变化' } ]" :key="row.title"><span>0{{ i + 1 }}</span><b>{{ row.title }}</b><small>{{ row.detail }}</small></div></div><div class="android-benefits"><div class="large-number">短路径<span>变成习惯</span></div><p>让用户每次记完都获得一点确定感，<br>隔天更愿意再次打开 Android。</p><div class="check-line"><Icon name="check" /> 首页入口保持稳定，减少寻找</div><div class="check-line"><Icon name="check" /> 按日回看，降低补记压力</div><div class="check-line"><Icon name="check" /> 温和提醒，不制造记账焦虑</div></div></div>
      <div v-if="index === 6" class="two-panels android-experience-panels"><div class="technical-panel"><div class="panel-label"><Icon name="phone" /> Android · 现场记录</div><h3>让手机成为最短入口</h3><p>Compose + Material 3 · 状态驱动界面</p><div class="android-shot-grid" aria-label="Android 真实界面预览"><figure class="android-shot"><div class="android-shot-status"><span>9:41</span><span>▰</span></div><img src="/defense/moon.jpg" alt="记账首页湖畔背景" /><div class="android-shot-card"><b>10月</b><span>支出 <strong>¥50.50</strong></span><span>收入 <em>¥0.00</em></span></div><figcaption>首页 · 按日账单与月汇总</figcaption></figure><figure class="android-shot"><div class="android-shot-status"><span>9:41</span><span>▰</span></div><img src="/defense/tree.jpg" alt="记账输入界面树木背景" /><div class="android-shot-card"><b>记一笔</b><span>金额优先</span><span>一步确认入账</span></div><figcaption>快捷键盘 · 一步确认落库</figcaption></figure></div><ul><li>底部导航保持记账、计划、资产、我的上下文</li><li>本地状态先更新，网络状态不打断输入</li></ul></div><div class="technical-panel dark-panel"><div class="panel-label"><Icon name="chat" /> QQ Bot · 创新延伸</div><h3>不打开 App，也能记一笔</h3><p>把“想起来却懒得打开”的阻力降到最低</p><div class="contract-row"><span>用户发送</span><b>午餐 20 元</b></div><div class="contract-row"><span>机器人解析</span><b>金额 · 分类 · 时间</b></div><div class="contract-row"><span>确认回执</span><b>已记入今日账单</b></div><div class="contract-row"><span>Android 回看</span><b>预算与长期管理</b></div><div class="panel-footnote">QQ Bot 负责入口，Android 负责完整体验。</div></div></div>
      <div v-if="index === 7" class="challenge-grid"><div><span class="challenge-number">01</span><h3>让第一笔足够简单</h3><p>金额优先、分类可后置，避免用户在第一屏就被选项劝退。</p><div class="code-comparison"><s>打开 → 找分类 → 填表单</s><b>打开 → 输入 → 确认</b></div><small>Android Quick Add<br>StateFlow 即时更新页面反馈</small></div><div><span class="challenge-number">02</span><h3>让离线记录不丢失</h3><p>网络不稳定时，账仍然可以记；恢复后再同步，不要求重复输入。</p><div class="version-demo"><span>本地 Room</span><Icon name="arrow" :size="16" /><b>增量同步</b></div><small>Room v18 迁移链<br>server_id 去重 · 版本保护</small></div><div><span class="challenge-number">03</span><h3>让 QQ Bot 值得信任</h3><p>自然语言可以轻，但入账必须可确认、可追踪、不可重复。</p><div class="engine-steps"><span>解析</span><span>确认</span><span>回执</span></div><small>事件去重 · 绑定校验<br>Android 负责长期回看与管理</small></div></div>
      <div v-if="index === 8" class="demo-layout"><div class="demo-input-panel"><span class="demo-badge"><span></span> 离线交互原型</span><h3>今天，想记点什么？</h3><form @submit.prevent="record"><label for="demo-utterance">一句话记账</label><input id="demo-utterance" v-model="utterance" maxlength="80" placeholder="例如：午饭 28 元" @input="saved = false; demoError = ''"><div class="sample-buttons"><button v-for="text in ['午饭 28 元', '奶茶 15 元', '地铁 4 元']" :key="text" type="button" @click="sample(text)">{{ text }}</button></div><button class="d-button d-primary" type="submit" :disabled="saved">{{ saved ? '演示记录已确认' : '确认演示记录' }}<Icon :name="saved ? 'check' : 'arrow'" :size="17" /></button></form><p class="demo-explainer">本页使用本地规则识别单笔数字金额，<br>不调用 AI，也不写入真实账本。</p><p v-if="demoError" class="demo-error" role="alert">{{ demoError }}</p></div><div class="demo-result-panel" aria-live="polite"><div class="panel-label"><Icon name="spark" /> 从表达，到结构化记录</div><div class="receipt"><div class="receipt-icon"><Icon :name="saved ? 'check' : 'book'" :size="26" /></div><span>{{ saved ? '已添加至演示账本' : '识别结果预览' }}</span><strong>{{ parsed ? formatMoney(parsed.minor) : '等待有效金额' }}</strong><div><span>收支类型</span><b>支出</b></div><div><span>分类</span><b>{{ parsed?.category || '—' }}</b></div><div><span>记录内容</span><b>{{ utterance || '—' }}</b></div><footer>{{ saved ? '这一笔，让生活更有数。' : '确认前，始终保留检查的机会。' }}</footer></div></div></div>
      <div v-if="index === 9" class="quality"><div class="quality-stats"><div><span>Android 单元测试</span><strong>301<small> / 301</small></strong><b><Icon name="check" :size="14" /> 验证通过</b></div><div><span>Debug APK</span><strong>1<small> 个</small></strong><b><Icon name="check" :size="14" /> 构建成功</b></div><div><span>核心 ViewModel</span><strong>5<small> 组</small></strong><b><Icon name="check" :size="14" /> 场景覆盖</b></div></div><div class="quality-details"><div><Icon name="shield" :size="28" /><h3>先保证一笔不丢</h3><p>覆盖快速记账、账单列表、预算、资产、AI 入口和同步相关 ViewModel。</p></div><div><Icon name="note" :size="28" /><h3>证据边界清晰</h3><p>验证记录来自 2026-09-30 云环境，未覆盖真机兼容性、性能压测及完整安全审计。</p></div></div><div class="evidence-note">Android 301 / 301 · JDK 17 · Android SDK · Debug APK 构建成功</div></div>
      <div v-if="index === 10" class="roadmap"><div class="roadmap-intro"><Icon name="leaf" :size="32" /><h3>已经形成的 Android 闭环</h3><p>想起 → 记录 → 反馈 → 再回来</p></div><div class="roadmap-grid"><div v-for="(item, i) in [{ phase: '低摩擦', title: '让入口更近一步', text: '探索桌面小组件、通知栏快捷入口和更快的金额输入。' }, { phase: '可持续', title: '让反馈更温和', text: '完善连续记录、可控提醒和预算反馈，帮助习惯而不是制造焦虑。' }, { phase: '可延伸', title: '让 QQ Bot 更可靠', text: '增强自然语言解析、确认回执和隐私设置，让聊天入口与 Android 同一账本。' } ]" :key="item.phase"><span class="roadmap-dot"></span><small>规划 0{{ i + 1 }} · {{ item.phase }}</small><h3>{{ item.title }}</h3><p>{{ item.text }}</p></div></div></div>
    </template>
    <div class="slide-footer"><span><i></i> 让记录更简单，让生活更清晰。</span><span>{{ String(index + 1).padStart(2, '0') }} <i>/</i> 12</span></div>
  </article>
</template>
